// Sample database of names and tasks
const tasksDatabase = [
    "Find John Doe and take a picture with him doing a 'L' on his forehead.",
    "Ask Jane Smith to teach you a word in her native language.",
    "Convince Emily Johnson to dance with you for 30 seconds and capture it on video.",
    // Add more names and tasks here
]

const participantsDatabase = [
    "Jakub Bartůněk",
    "Valentine De Voghel",
    "Valtteri Tuominen",
    "Manon Soenen",
    "Morgane Hemingway",
    "Alexine Simon",
    "Frederique Masse",
    "Lovisa Grahn",
    "Mark Rastert",
    "Sofia Gomes",
    "Marianne Leduc",
    "Cordula von Heyl",
    "Nick Hebenstreit",
    "Eduarda Dionisio",
    "Amica Swanepoel",
    "Elise Gardeyn",
    "Marius Løfqvist",
    "Alessandro Iencenella",
    "Mariana Alves",
    "Julia Buchner",
    "Mona Volmich",
    "Hendrik Holzwarth",
    "Pauline Halloy",
    "Amelie Topf",
    "Bartłomiej Jawor",
    "Arielle Chaîné",
    "Catherine Carpentier-Desjardins",
    "Sristi Ramoutar",
    "Nina Seidel",
    "Knut Bugge",
    "Isa-May Beauchamp",
    "Bianca Baldassarre",
    "Dana Langeler",
    "Justus Dorsel",
    "Johanna Schoele",
    "Sebastian Mueller",
    "Dulce Lopez",
    "Zuhal Fedai",
    "Viktor Svalstedt",
    "Niels Vignaux",
    "Almog Adato",
    "Janosh Huyse",
    "Pontus Hedman",
    "Vincent Cautaerts",
    "Jef De Koker",
    "Théodore Olaru",
    "Josefin Olsson",
    "Gabriel Probst",
    "Lucas Heule",
    "Anastasia Abe",
    "Jolien Van de Walle",
    "Marianne Kersten",
    "Amanda Puerto-Lichtenberg",
    "Tejas Kochar",
    "Aditya Narayan Shahi",
    "Raphael Tasseel",
    "Neus Bosch Matheu",
    "Eric Oldgren",
    "Bradley van Hooff",
    "Francesco La Rosa",
    "Alicja Jonczyk",
    "Edoardo Bargis",
    "Paul Mathiot",
    "Asmita Johri",
    "Grzegorz Statkiewicz",
    "Alyssa Popescu",
    "Anders Eiersted Molzen",
    "Marie Albrecht",
    "Katrine Broegger Jensen",
    "Rémi Gardette",
    "Neshon Missaghian",
    "Hsin Ju Liou",
    "Maria Francesca Spada",
    "David Weber",
    "Martha Boosten",
    "Timon Dries",
    "Maria Carolina Hüning",
    "Carl Lingström",
    "Philippe Carrier",
    "Caroline Borup Jeppesen",
    "Matti Lehmann",
    "John Larsson",
    "Dilara Baran",
    "Jeremy Racine",
    "Laura Linuesa Domenech",
    "Sabina Ghita",
    "Xiao Xiang",
    "Gabriella Bjaaland",
    "Ruadhán Mac Giolla Phádraig",
    "Sven Wendler",
    "Robert Andersson",
    "Cristian Safta",
    "Viktor Kjellsson",
    "Joe Rizk",
    "Erik Bessö",
    "Clara Wimmelmann",
    "Ben René Bjørsvik",
    "Rohan Shetty",
    "Marcin Kleszcz",
    "Junzhe Chen",
    "Herald Nakpil",
    "Thomas De Masi",
    "Maxime Rufer",
    "Yann Boudigou",
    "Zacharie Puippe",
    "Amine Bousseta",
    "Kim Huynh",
    "Speich Lui",
    "Quentin Devaud",
    "Augustin Henry",
    "Tahiry Arintsoa",
    "Yann Savioz",
    "Aline Marcionetti-Rusconi",
    "Heloise Fabbretti",
    "Alistair Hay",
    "Thomas Bonnet",
    "Guillaume Granger",
    "Cyril Udriot",
    "Audrey Adehossi",
    "Oriane Petit-Phar",
    "Céline Kalbermatten",
    "Chloé Dau",
    "Tim Lücking",
    "Milou Ordonneau",
    "Lucie Zhou",
    "Mara Blöchlinger",
    "Ines Acevedo",
    "Colin Hafen",
    "Luc Scholl",
    "Clara Gloge",
    "Noah Trippens"
  ]
  

function getRandomTask() {
    const randomIndex = Math.floor(Math.random() * tasksDatabase.length);
    return tasksDatabase[randomIndex];
}

function checkName() {
    const name = document.getElementById("nameInput").value;
    const taskResult = document.getElementById("taskResult");

    if (participantsDatabase.includes(name)) {
        taskResult.textContent = getRandomTask();
    } else {
        taskResult.textContent = "Sorry, your name is not in the database. Try again!";
    }
}
